# Generated by Django 4.0.4 on 2022-04-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220428_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
